Makefile
Teaching-projects/-SZE-MOSZE-2020-CADbol-ny--CLOSED pull request #12
Opened 2020-11-03 07:51 UTC by dobaybalazs

Makefile elkészítve.

2020-11-03 10:21 UTC, hegyhati requested changes

2020-11-03 10:21 UTC, hegyhati commented on .github/workflows/test.yml
> +        run: make permission
az ilyet azert ne tegyuk make-be.

2020-11-03 10:21 UTC, hegyhati commented on Makefile
> +	$(COMP) -c units.cpp
tessek elolvasni, amit a csoportba irtam.

2020-11-03 10:47 UTC, dobaybalazs commented
Változtatások elkészítve @hegyhati , elnézést a figyelmetlenségért.

2020-11-04 15:46 UTC, hegyhati approved these changes

2020-11-04 15:46 UTC, merged