Jsonparser
Teaching-projects/-SZE-MOSZE-2020-CADbol-ny--CLOSED pull request #6
Opened 2020-10-15 16:57 UTC by dobaybalazs

jsonparser elkészítve.

2020-10-18 16:30 UTC, wajzy requested changes
A kisebb-nagyobb jelzett gondokon túl a legfőbb probléma, hogy tökéletesen formázott JSON tartalmat feltételezel. Itt az ideje felkészíteni néhány, könnyen előforduló hibára a perzert, pl. hiányzó :-ra, "-re, stb.

2020-10-18 16:30 UTC, wajzy commented on jsonparser.cpp
> +		throw 1;
Hát, ettől nem lesz sokkal okosabb, aki látja.

2020-10-18 16:30 UTC, wajzy commented on jsonparser.cpp
> +	std::string line, line1, line2;
Nem valami beszédesek a változónevek. Mondjuk a key és a value egy fokkal kifejezőbb lenne.

2020-10-18 16:30 UTC, wajzy commented on jsonparser.cpp
> +std::map< std::string, std::string> JsonParser::ParseString(std::string& text){
Biztosan szükség van két, ennyire hasonló függvényre? Nem lehet valahogy rövidíteni, az egyik működését a másikra visszavezetni?

2020-10-18 16:30 UTC, wajzy commented on units.cpp
>  		throw 1;
Ehhh...

2020-10-19 12:50 UTC, dobaybalazs commented
@wajzy A kért változtatásokat elkészítéttem, a conflictok a változtatások elfogadása után kerülnek majd feloldásra.

2020-10-20 13:17 UTC, wajzy approved these changes
Látható, hogy bizonyos típusú hibák nem hozzák zavarba a parzert, még ha nem is teljes körű az ellenőrzés, elfogadom. Ettől még a megjegyzésem továbbra is érvényes, egy commitot szerintem megérne a javítás.

2020-10-20 13:17 UTC, wajzy commented on jsonparser.cpp
> +		throw 1;
Úgy látom, nem voltam elég egyértelmű. Nem a változók nevei zavartak, hanem a throw 1-ben az 1. Egy hónap múlva senki nem fog emlékezni, mi váltja ki az 1-es típusú hibát, meg mi a 3497-eset. Azon kívül, hogy a kivétel típusát is lehetne valami alkalmasabbra választani, a számokat is lehetne pl. egy beszédesebb nevű enum konstanssal helyettesíteni.

2020-10-20 20:45 UTC, dobaybalazs commented
@wajzy A conflictok feloldásra kerültek, az exception módosítva lett.

2020-10-24 14:10 UTC, wajzy approved these changes
OK

2020-10-24 14:10 UTC, merged